# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'System.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Container = QtWidgets.QGroupBox(self.centralwidget)
        self.Container.setGeometry(QtCore.QRect(100, 20, 531, 401))
        self.Container.setStyleSheet("QGroupBox {\n"
"    border: 1px solid black;\n"
"    background-color: #00BFFF;\n"
"}")
        self.Container.setObjectName("Container")
        self.duration_edit = QtWidgets.QLineEdit(self.Container)
        self.duration_edit.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.duration_edit.setObjectName("duration_edit")
        self.duration = QtWidgets.QLabel(self.Container)
        self.duration.setGeometry(QtCore.QRect(30, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.duration.setFont(font)
        self.duration.setObjectName("duration")
        self.insured_age = QtWidgets.QLabel(self.Container)
        self.insured_age.setGeometry(QtCore.QRect(30, 120, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insured_age.setFont(font)
        self.insured_age.setObjectName("insured_age")
        self.insured_age_edit = QtWidgets.QLineEdit(self.Container)
        self.insured_age_edit.setGeometry(QtCore.QRect(120, 120, 113, 20))
        self.insured_age_edit.setObjectName("insured_age_edit")
        self.insured_sex = QtWidgets.QLabel(self.Container)
        self.insured_sex.setGeometry(QtCore.QRect(30, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insured_sex.setFont(font)
        self.insured_sex.setObjectName("insured_sex")
        self.insured_sex_edit = QtWidgets.QLineEdit(self.Container)
        self.insured_sex_edit.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.insured_sex_edit.setObjectName("insured_sex_edit")
        self.car_age = QtWidgets.QLabel(self.Container)
        self.car_age.setGeometry(QtCore.QRect(30, 200, 54, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.car_age.setFont(font)
        self.car_age.setObjectName("car_age")
        self.car_age_edit = QtWidgets.QLineEdit(self.Container)
        self.car_age_edit.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.car_age_edit.setObjectName("car_age_edit")
        self.marital = QtWidgets.QLabel(self.Container)
        self.marital.setGeometry(QtCore.QRect(30, 240, 54, 12))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.marital.setFont(font)
        self.marital.setObjectName("marital")
        self.marital_edit = QtWidgets.QLineEdit(self.Container)
        self.marital_edit.setGeometry(QtCore.QRect(120, 240, 113, 20))
        self.marital_edit.setObjectName("marital_edit")
        self.car_use_edit = QtWidgets.QLineEdit(self.Container)
        self.car_use_edit.setGeometry(QtCore.QRect(400, 80, 113, 20))
        self.car_use_edit.setText("")
        self.car_use_edit.setObjectName("car_use_edit")
        self.car_use = QtWidgets.QLabel(self.Container)
        self.car_use.setGeometry(QtCore.QRect(280, 80, 54, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.car_use.setFont(font)
        self.car_use.setObjectName("car_use")
        self.credit_score_edit = QtWidgets.QLineEdit(self.Container)
        self.credit_score_edit.setGeometry(QtCore.QRect(400, 120, 113, 20))
        self.credit_score_edit.setObjectName("credit_score_edit")
        self.credit_score = QtWidgets.QLabel(self.Container)
        self.credit_score.setGeometry(QtCore.QRect(280, 120, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.credit_score.setFont(font)
        self.credit_score.setObjectName("credit_score")
        self.region_edit = QtWidgets.QLineEdit(self.Container)
        self.region_edit.setGeometry(QtCore.QRect(400, 160, 113, 20))
        self.region_edit.setObjectName("region_edit")
        self.region = QtWidgets.QLabel(self.Container)
        self.region.setGeometry(QtCore.QRect(280, 160, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.region.setFont(font)
        self.region.setObjectName("region")
        self.total_miles_drive_edit = QtWidgets.QLineEdit(self.Container)
        self.total_miles_drive_edit.setGeometry(QtCore.QRect(400, 200, 113, 20))
        self.total_miles_drive_edit.setObjectName("total_miles_drive_edit")
        self.total_miles_drive = QtWidgets.QLabel(self.Container)
        self.total_miles_drive.setGeometry(QtCore.QRect(280, 200, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.total_miles_drive.setFont(font)
        self.total_miles_drive.setObjectName("total_miles_drive")
        self.territory_edit = QtWidgets.QLineEdit(self.Container)
        self.territory_edit.setGeometry(QtCore.QRect(400, 240, 113, 20))
        self.territory_edit.setObjectName("territory_edit")
        self.territory = QtWidgets.QLabel(self.Container)
        self.territory.setGeometry(QtCore.QRect(280, 240, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.territory.setFont(font)
        self.territory.setObjectName("territory")
        self.insurance_fee = QtWidgets.QLabel(self.Container)
        self.insurance_fee.setGeometry(QtCore.QRect(90, 350, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.insurance_fee.setFont(font)
        self.insurance_fee.setStyleSheet("font-weight: bold;")
        self.insurance_fee.setObjectName("insurance_fee")
        self.insurance_fee_edit = QtWidgets.QLineEdit(self.Container)
        self.insurance_fee_edit.setGeometry(QtCore.QRect(330, 350, 113, 20))
        self.insurance_fee_edit.setReadOnly(True)
        self.insurance_fee_edit.setObjectName("insurance_fee_edit")
        self.done = QtWidgets.QPushButton(self.Container)
        self.done.setGeometry(QtCore.QRect(320, 290, 81, 31))
        self.done.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #f0f0f0; /* 设置背景颜色 */\n"
"    border: 1px solid #c0c0c0; /* 设置边框 */\n"
"    border-radius: 5px; /* 设置圆角 */\n"
"    padding: 5px 10px; /* 设置内边距 */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.5); /* 设置阴影 */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0; /* 按钮按下时的背景颜色 */\n"
"    color:white;\n"
"}")
        self.done.setObjectName("done")
        self.clear = QtWidgets.QPushButton(self.Container)
        self.clear.setGeometry(QtCore.QRect(140, 290, 81, 31))
        self.clear.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #f0f0f0; /* 设置背景颜色 */\n"
"    border: 1px solid #c0c0c0; /* 设置边框 */\n"
"    border-radius: 5px; /* 设置圆角 */\n"
"    padding: 5px 10px; /* 设置内边距 */\n"
"    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.5); /* 设置阴影 */\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0; /* 鼠标悬停时的背景颜色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0; /* 按钮按下时的背景颜色 */\n"
"    color:white\n"
"}")
        self.clear.setObjectName("clear")
        self.title = QtWidgets.QLabel(self.Container)
        self.title.setGeometry(QtCore.QRect(80, 13, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("font-weight: bold;\n"
"letter-spacing: 2px;")
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.duration_edit.raise_()
        self.duration.raise_()
        self.insured_age.raise_()
        self.insured_age_edit.raise_()
        self.insured_sex.raise_()
        self.insured_sex_edit.raise_()
        self.car_age_edit.raise_()
        self.marital.raise_()
        self.marital_edit.raise_()
        self.car_use_edit.raise_()
        self.car_use.raise_()
        self.credit_score_edit.raise_()
        self.credit_score.raise_()
        self.region_edit.raise_()
        self.region.raise_()
        self.total_miles_drive_edit.raise_()
        self.total_miles_drive.raise_()
        self.territory_edit.raise_()
        self.territory.raise_()
        self.insurance_fee.raise_()
        self.insurance_fee_edit.raise_()
        self.done.raise_()
        self.clear.raise_()
        self.car_age.raise_()
        self.title.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.duration.setText(_translate("MainWindow", "Duration:"))
        self.insured_age.setText(_translate("MainWindow", "Insured Age:"))
        self.insured_sex.setText(_translate("MainWindow", "Insured Sex:"))
        self.car_age.setText(_translate("MainWindow", "Car Age:"))
        self.marital.setText(_translate("MainWindow", "Marital:"))
        self.car_use.setText(_translate("MainWindow", "Car Use:"))
        self.credit_score.setText(_translate("MainWindow", "Credit Score:"))
        self.region.setText(_translate("MainWindow", "Region:"))
        self.total_miles_drive.setText(_translate("MainWindow", "Total-miles Drive:"))
        self.territory.setText(_translate("MainWindow", "Territory:"))
        self.insurance_fee.setText(_translate("MainWindow", "The insurance fee will be:"))
        self.done.setText(_translate("MainWindow", "DONE"))
        self.clear.setText(_translate("MainWindow", "CLEAR"))
        self.title.setText(_translate("MainWindow", "Insurance cost calculation system"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
